# https://travis-ci.org/burgerbecky/wslwinreg
# Docs for Travis https://docs.travis-ci.com/

# Python testing
language: python

# Cache the python pip and environment folders
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"

# Only track the master branch, don't process pull requests
branches:
  only:
    - master

# Allow apt-update
addons:
  apt:
    update: true

matrix:
  include:
    # Windows builds
    - name: "Python2.7.18 on Windows"
      os: windows
      language: sh
      python: "2.7"
      env: TOXENV=py27
      before_install:
        - choco install python2 --version=2.7.18
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"

    # Added pip install pip==19.1.1 to fix NameError: name 'platform_system' is not defined error
    # Note: pip 19.1.1 is the last version that supports Python 3.4
    - name: "Python3.4.4 on Windows"
      os: windows
      language: sh
      python: "3.4"
      env: TOXENV=py34
      before_install:
        - choco install python3 --version=3.4.4
        - export PATH="/c/Python34:/c/Python34/Scripts:$PATH"
        - python -m pip install pip==19.1.1

    - name: "Python3.5.4 on Windows"
      os: windows
      language: sh
      python: "3.5"
      env: TOXENV=py35
      before_install:
        - choco install python3 --version=3.5.4
        - export PATH="/c/Python35:/c/Python35/Scripts:$PATH"

    - name: "Python3.6.8 on Windows"
      os: windows
      language: sh
      python: "3.6"
      env: TOXENV=py36
      before_install:
        - choco install python3 --version=3.6.8
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"

    - name: "Python3.7.9 on Windows"
      os: windows
      language: sh
      python: "3.7"
      env: TOXENV=py37
      before_install:
        - choco install python3 --version=3.7.9
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

    - name: "Python3.8.6 on Windows"
      os: windows
      language: sh
      python: "3.8"
      env: TOXENV=py38
      before_install:
        - choco install python3 --version=3.8.6
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

    - name: "Python3.9.0 on Windows"
      os: windows
      language: sh
      python: "3.9"
      env: TOXENV=py39
      before_install:
        - choco install python3 --version=3.9.0
        - export PATH="/c/Python39:/c/Python39/Scripts:$PATH"

# Install python packages needed for this test and get versions for log
install:
  - pip install .
  - pip install tox-travis wheel codecov coverage pathlib2
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

# Tox does all the work
script:
  - tox

# Output the errors, if any
after_failure:
  - more temp/tox/log/* | cat
  - more temp/tox/*/log/* | cat

# Send a pass/fail to us
notifications:
  slack:
    rooms:
      secure: T4nFowKbMzdZikD9D0kKg3CYV/NVtypUrfj5NruaZgsArw3Fo0RZj1/CQacXVR8qWBGjpqxwhDDkBEKFjq5e/++GsrUxoLL+Rgz8hn8VVUgV4q8+I7W4WDPybc1pEervJNqqwCq7oCiNen4ZrKzojVuNhO9HVAEDXRNfHzM9k/GvIOOpQzK6QB8tgfXTjoT8MZL5MjBvzFje755XgytELXlgCmcd+2wDXAUBwlgfxMtGC7UZhng5fS/6JmYYoBLATebpKMLUPcLbfHRZ3vb8x2fKnEDXF1YSAjry+Ade8bj/CdoM2SBZjjhsh7L+EoveWY0SXXFdtqjFMZu6zLUTRhACpmID/ANYjZYCUyeNIOzjNml1WhxnD11LGYhmB3V7164FEYdxtq5Z1QSwsH1cmA5u8loitM9nkl1wgc+IBtlrNTpDj7S75iRFxa4mr5hZfBADJy9Tpm5GzX+i/14zYFcE+0f6CnWebGfcTd9Js+vKIKoa4ttoXNhGERBsLy5S2QcBRS5yqSh8/dgi0GsnRBYYEfpOdV9H5mgq4WNVJnsntANwYk/Q9FvTmrrbnteb1oY8Tvf4GvaHioKNLbqbTXNSTdFozbrYLPrNoFGDGQBl767JBtQChcnfsHv78c3BluaLlCU8ikwYzJsrx9KqpXWuc06c+JGVC1qVLR9kZcA=
    on_success: always
    on_failure: always
  email:
    on_success: change
    on_failure: always
