# Name of this workflow
name: WSLWinReg for Python

# Only process when a new version is pushed on master
on:
  push:
    branches:
      - "master"

jobs:
  "Run_Pytest":
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # Here are all the operating systems and python versions to test on.
      matrix:
        name:
          - "windows-2022-py36"
          - "windows-2022-py37"
          - "windows-2022-py38"
          - "windows-2022-py39"
          - "windows-2022-py310"
          - "windows-2022-py311"
          - "windows-2022-py312"
          - "windows-2022-py313"
          - "windows-2025-py313"
          - "windows-2025-pypy310"
          # Disabled pypy27 since it crashes on Github, but
          # it passes locally on Windows 10
          # - "windows-2025-pypy27"
          # Specific data for each version being built
        include:
          # Windows 2022 Server
          - name: "windows-2022-py36"
            python: "3.6"
            os: "windows-2022"
            tox_env: "py36"
          - name: "windows-2022-py37"
            python: "3.7"
            os: "windows-2022"
            tox_env: "py37"
          - name: "windows-2022-py38"
            python: "3.8"
            os: "windows-2022"
            tox_env: "py38"
          - name: "windows-2022-py39"
            python: "3.9"
            os: "windows-2022"
            tox_env: "py39"
          - name: "windows-2022-py310"
            python: "3.10"
            os: "windows-2022"
            tox_env: "py310"
          - name: "windows-2022-py311"
            python: "3.11"
            os: "windows-2022"
            tox_env: "py311"
          - name: "windows-2022-py312"
            python: "3.12"
            os: "windows-2022"
            tox_env: "py312"
          - name: "windows-2022-py313"
            python: "3.13"
            os: "windows-2022"
            tox_env: "py313"
            # Windows 2025 Server
          - name: "windows-2025-py313"
            python: "3.13"
            os: "windows-2025"
            tox_env: "py313"
          - name: "windows-2025-pypy27"
            python: "pypy2.7"
            os: "windows-2025"
            tox_env: "pypy"
          - name: "windows-2025-pypy310"
            python: "pypy3.10"
            os: "windows-2025"
            tox_env: "pypy3"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          python -V
          pytest
