# Name of this workflow
name: WSLWinReg for Python

# Only process when a new version is pushed on master
on:
  push:
    branches:
      - "master"

jobs:
  "Run_Pytest":
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # Here are all the operating systems and python versions to test on.
      matrix:
        name:
          - "windows-2019-py36"
          - "windows-2019-py37"
          - "windows-2019-py38"
          - "windows-2019-py39"
          - "windows-2019-py310"
          - "windows-2019-py311"
          - "windows-2019-py312"
          - "windows-2022-py312"
          # Specific data for each version being built
        include:
          # Windows 2019 Server
          - name: "windows-2019-py36"
            python: "3.6"
            os: "windows-2019"
            tox_env: "py36"
          - name: "windows-2019-py37"
            python: "3.7"
            os: "windows-2019"
            tox_env: "py37"
          - name: "windows-2019-py38"
            python: "3.8"
            os: "windows-2019"
            tox_env: "py38"
          - name: "windows-2019-py39"
            python: "3.9"
            os: "windows-2019"
            tox_env: "py39"
          - name: "windows-2019-py310"
            python: "3.10"
            os: "windows-2019"
            tox_env: "py310"
          - name: "windows-2019-py311"
            python: "3.11"
            os: "windows-2019"
            tox_env: "py311"
          - name: "windows-2019-py312"
            python: "3.12"
            os: "windows-2019"
            tox_env: "py312"
          # Windows 2019 Server
          - name: "windows-2022-py312"
            python: "3.12"
            os: "windows-2022"
            tox_env: "py312"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          python -V
          pytest
